[project]
name = "02-embeddings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.0.5",
    "langchain-community>=0.4.1",
    "langchain-text-splitters>=1.0.0",
    "pymupdf>=1.26.6",
]
